services:
  srv-pakman:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - VITE_RUUVI_SERIAL=${VITE_RUUVI_SERIAL}
      - VITE_INFLUXDB_BUCKET=${VITE_INFLUXDB_BUCKET}
      - VITE_INFLUXDB_ORG=${VITE_INFLUXDB_ORG}
      - VITE_INFLUXDB_URL=${VITE_INFLUXDB_URL}
      - VITE_INFLUXDB_TOKEN=${VITE_INFLUXDB_TOKEN}
    networks:
      - overlay-net
    ports:
      - 8080:80

networks:
    overlay-net:
        external: true
        name: overlay-net